# Generated by Django 5.1.3 on 2024-11-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
