# Generated by Django 5.1.2 on 2024-10-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_rename_id_producto_condiciones_producto_and_more'),
        ('ticket', '0003_remove_ticket_id_promocion_ticket_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promociones.promociones'),
        ),
    ]
