# Generated by Django 5.1.2 on 2024-10-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='id_rol',
            new_name='rol',
        ),
    ]
