# Generated by Django 5.1.3 on 2024-11-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='banner',
            field=models.ImageField(upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='botonMenu',
            field=models.ImageField(upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='botonReservation',
            field=models.ImageField(upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='botonSeguimientoDePedido',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
