# Generated by Django 5.1.2 on 2024-10-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condiciones',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='promociones',
            old_name='id_condiciones',
            new_name='condiciones',
        ),
    ]
