# Generated by Django 5.1.2 on 2024-10-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='id_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='id_mesa',
            new_name='mesa',
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='id_ticket',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='id_tipo_de_pedido',
            new_name='tipo_de_pedido',
        ),
    ]
