# Generated by Django 5.1.2 on 2024-11-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0004_alter_comanda_ticket'),
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesa.mesa'),
        ),
    ]
