# Generated by Django 5.1.2 on 2024-10-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='id_ticket',
            new_name='ticket',
        ),
    ]
